# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/gabriel/miniconda3/lib/python3.10/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/gabriel/miniconda3/lib/python3.10/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gabriel/Bureau/paxos_8

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gabriel/Bureau/paxos_8

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/gabriel/miniconda3/lib/python3.10/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/gabriel/miniconda3/lib/python3.10/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gabriel/Bureau/paxos_8/CMakeFiles /home/gabriel/Bureau/paxos_8//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gabriel/Bureau/paxos_8/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/gabriel/Bureau/paxos_8/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PaxOS8

# Build rule for target.
PaxOS8: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PaxOS8
.PHONY : PaxOS8

# fast build rule for target.
PaxOS8/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/build
.PHONY : PaxOS8/fast

interface/LovyanGFX/LGFX_SDL.o: interface/LovyanGFX/LGFX_SDL.cpp.o
.PHONY : interface/LovyanGFX/LGFX_SDL.o

# target to build an object file
interface/LovyanGFX/LGFX_SDL.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/LGFX_SDL.cpp.o
.PHONY : interface/LovyanGFX/LGFX_SDL.cpp.o

interface/LovyanGFX/LGFX_SDL.i: interface/LovyanGFX/LGFX_SDL.cpp.i
.PHONY : interface/LovyanGFX/LGFX_SDL.i

# target to preprocess a source file
interface/LovyanGFX/LGFX_SDL.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/LGFX_SDL.cpp.i
.PHONY : interface/LovyanGFX/LGFX_SDL.cpp.i

interface/LovyanGFX/LGFX_SDL.s: interface/LovyanGFX/LGFX_SDL.cpp.s
.PHONY : interface/LovyanGFX/LGFX_SDL.s

# target to generate assembly for a file
interface/LovyanGFX/LGFX_SDL.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/LGFX_SDL.cpp.s
.PHONY : interface/LovyanGFX/LGFX_SDL.cpp.s

interface/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.o: interface/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.c.o
.PHONY : interface/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.o

# target to build an object file
interface/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.c.o
.PHONY : interface/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.c.o

interface/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.i: interface/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.c.i
.PHONY : interface/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.i

# target to preprocess a source file
interface/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.c.i
.PHONY : interface/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.c.i

interface/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.s: interface/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.c.s
.PHONY : interface/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.s

# target to generate assembly for a file
interface/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.c.s
.PHONY : interface/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.c.s

interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.o: interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.c.o
.PHONY : interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.o

# target to build an object file
interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.c.o
.PHONY : interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.c.o

interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.i: interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.c.i
.PHONY : interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.i

# target to preprocess a source file
interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.c.i
.PHONY : interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.c.i

interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.s: interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.c.s
.PHONY : interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.s

# target to generate assembly for a file
interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.c.s
.PHONY : interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.c.s

interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.o: interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.c.o
.PHONY : interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.o

# target to build an object file
interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.c.o
.PHONY : interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.c.o

interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.i: interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.c.i
.PHONY : interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.i

# target to preprocess a source file
interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.c.i
.PHONY : interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.c.i

interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.s: interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.c.s
.PHONY : interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.s

# target to generate assembly for a file
interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.c.s
.PHONY : interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.c.s

interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.o: interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.c.o
.PHONY : interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.o

# target to build an object file
interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.c.o
.PHONY : interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.c.o

interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.i: interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.c.i
.PHONY : interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.i

# target to preprocess a source file
interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.c.i
.PHONY : interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.c.i

interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.s: interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.c.s
.PHONY : interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.s

# target to generate assembly for a file
interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.c.s
.PHONY : interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.c.s

interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.o: interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.c.o
.PHONY : interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.o

# target to build an object file
interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.c.o
.PHONY : interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.c.o

interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.i: interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.c.i
.PHONY : interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.i

# target to preprocess a source file
interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.c.i
.PHONY : interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.c.i

interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.s: interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.c.s
.PHONY : interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.s

# target to generate assembly for a file
interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.c.s
.PHONY : interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.c.s

interface/LovyanGFX/lgfx/utility/lgfx_pngle.o: interface/LovyanGFX/lgfx/utility/lgfx_pngle.c.o
.PHONY : interface/LovyanGFX/lgfx/utility/lgfx_pngle.o

# target to build an object file
interface/LovyanGFX/lgfx/utility/lgfx_pngle.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/utility/lgfx_pngle.c.o
.PHONY : interface/LovyanGFX/lgfx/utility/lgfx_pngle.c.o

interface/LovyanGFX/lgfx/utility/lgfx_pngle.i: interface/LovyanGFX/lgfx/utility/lgfx_pngle.c.i
.PHONY : interface/LovyanGFX/lgfx/utility/lgfx_pngle.i

# target to preprocess a source file
interface/LovyanGFX/lgfx/utility/lgfx_pngle.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/utility/lgfx_pngle.c.i
.PHONY : interface/LovyanGFX/lgfx/utility/lgfx_pngle.c.i

interface/LovyanGFX/lgfx/utility/lgfx_pngle.s: interface/LovyanGFX/lgfx/utility/lgfx_pngle.c.s
.PHONY : interface/LovyanGFX/lgfx/utility/lgfx_pngle.s

# target to generate assembly for a file
interface/LovyanGFX/lgfx/utility/lgfx_pngle.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/utility/lgfx_pngle.c.s
.PHONY : interface/LovyanGFX/lgfx/utility/lgfx_pngle.c.s

interface/LovyanGFX/lgfx/utility/lgfx_qoi.o: interface/LovyanGFX/lgfx/utility/lgfx_qoi.c.o
.PHONY : interface/LovyanGFX/lgfx/utility/lgfx_qoi.o

# target to build an object file
interface/LovyanGFX/lgfx/utility/lgfx_qoi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/utility/lgfx_qoi.c.o
.PHONY : interface/LovyanGFX/lgfx/utility/lgfx_qoi.c.o

interface/LovyanGFX/lgfx/utility/lgfx_qoi.i: interface/LovyanGFX/lgfx/utility/lgfx_qoi.c.i
.PHONY : interface/LovyanGFX/lgfx/utility/lgfx_qoi.i

# target to preprocess a source file
interface/LovyanGFX/lgfx/utility/lgfx_qoi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/utility/lgfx_qoi.c.i
.PHONY : interface/LovyanGFX/lgfx/utility/lgfx_qoi.c.i

interface/LovyanGFX/lgfx/utility/lgfx_qoi.s: interface/LovyanGFX/lgfx/utility/lgfx_qoi.c.s
.PHONY : interface/LovyanGFX/lgfx/utility/lgfx_qoi.s

# target to generate assembly for a file
interface/LovyanGFX/lgfx/utility/lgfx_qoi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/utility/lgfx_qoi.c.s
.PHONY : interface/LovyanGFX/lgfx/utility/lgfx_qoi.c.s

interface/LovyanGFX/lgfx/utility/lgfx_qrcode.o: interface/LovyanGFX/lgfx/utility/lgfx_qrcode.c.o
.PHONY : interface/LovyanGFX/lgfx/utility/lgfx_qrcode.o

# target to build an object file
interface/LovyanGFX/lgfx/utility/lgfx_qrcode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/utility/lgfx_qrcode.c.o
.PHONY : interface/LovyanGFX/lgfx/utility/lgfx_qrcode.c.o

interface/LovyanGFX/lgfx/utility/lgfx_qrcode.i: interface/LovyanGFX/lgfx/utility/lgfx_qrcode.c.i
.PHONY : interface/LovyanGFX/lgfx/utility/lgfx_qrcode.i

# target to preprocess a source file
interface/LovyanGFX/lgfx/utility/lgfx_qrcode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/utility/lgfx_qrcode.c.i
.PHONY : interface/LovyanGFX/lgfx/utility/lgfx_qrcode.c.i

interface/LovyanGFX/lgfx/utility/lgfx_qrcode.s: interface/LovyanGFX/lgfx/utility/lgfx_qrcode.c.s
.PHONY : interface/LovyanGFX/lgfx/utility/lgfx_qrcode.s

# target to generate assembly for a file
interface/LovyanGFX/lgfx/utility/lgfx_qrcode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/utility/lgfx_qrcode.c.s
.PHONY : interface/LovyanGFX/lgfx/utility/lgfx_qrcode.c.s

interface/LovyanGFX/lgfx/utility/lgfx_tjpgd.o: interface/LovyanGFX/lgfx/utility/lgfx_tjpgd.c.o
.PHONY : interface/LovyanGFX/lgfx/utility/lgfx_tjpgd.o

# target to build an object file
interface/LovyanGFX/lgfx/utility/lgfx_tjpgd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/utility/lgfx_tjpgd.c.o
.PHONY : interface/LovyanGFX/lgfx/utility/lgfx_tjpgd.c.o

interface/LovyanGFX/lgfx/utility/lgfx_tjpgd.i: interface/LovyanGFX/lgfx/utility/lgfx_tjpgd.c.i
.PHONY : interface/LovyanGFX/lgfx/utility/lgfx_tjpgd.i

# target to preprocess a source file
interface/LovyanGFX/lgfx/utility/lgfx_tjpgd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/utility/lgfx_tjpgd.c.i
.PHONY : interface/LovyanGFX/lgfx/utility/lgfx_tjpgd.c.i

interface/LovyanGFX/lgfx/utility/lgfx_tjpgd.s: interface/LovyanGFX/lgfx/utility/lgfx_tjpgd.c.s
.PHONY : interface/LovyanGFX/lgfx/utility/lgfx_tjpgd.s

# target to generate assembly for a file
interface/LovyanGFX/lgfx/utility/lgfx_tjpgd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/utility/lgfx_tjpgd.c.s
.PHONY : interface/LovyanGFX/lgfx/utility/lgfx_tjpgd.c.s

interface/LovyanGFX/lgfx/utility/miniz.o: interface/LovyanGFX/lgfx/utility/miniz.c.o
.PHONY : interface/LovyanGFX/lgfx/utility/miniz.o

# target to build an object file
interface/LovyanGFX/lgfx/utility/miniz.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/utility/miniz.c.o
.PHONY : interface/LovyanGFX/lgfx/utility/miniz.c.o

interface/LovyanGFX/lgfx/utility/miniz.i: interface/LovyanGFX/lgfx/utility/miniz.c.i
.PHONY : interface/LovyanGFX/lgfx/utility/miniz.i

# target to preprocess a source file
interface/LovyanGFX/lgfx/utility/miniz.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/utility/miniz.c.i
.PHONY : interface/LovyanGFX/lgfx/utility/miniz.c.i

interface/LovyanGFX/lgfx/utility/miniz.s: interface/LovyanGFX/lgfx/utility/miniz.c.s
.PHONY : interface/LovyanGFX/lgfx/utility/miniz.s

# target to generate assembly for a file
interface/LovyanGFX/lgfx/utility/miniz.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/utility/miniz.c.s
.PHONY : interface/LovyanGFX/lgfx/utility/miniz.c.s

interface/LovyanGFX/lgfx/v1/LGFXBase.o: interface/LovyanGFX/lgfx/v1/LGFXBase.cpp.o
.PHONY : interface/LovyanGFX/lgfx/v1/LGFXBase.o

# target to build an object file
interface/LovyanGFX/lgfx/v1/LGFXBase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/LGFXBase.cpp.o
.PHONY : interface/LovyanGFX/lgfx/v1/LGFXBase.cpp.o

interface/LovyanGFX/lgfx/v1/LGFXBase.i: interface/LovyanGFX/lgfx/v1/LGFXBase.cpp.i
.PHONY : interface/LovyanGFX/lgfx/v1/LGFXBase.i

# target to preprocess a source file
interface/LovyanGFX/lgfx/v1/LGFXBase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/LGFXBase.cpp.i
.PHONY : interface/LovyanGFX/lgfx/v1/LGFXBase.cpp.i

interface/LovyanGFX/lgfx/v1/LGFXBase.s: interface/LovyanGFX/lgfx/v1/LGFXBase.cpp.s
.PHONY : interface/LovyanGFX/lgfx/v1/LGFXBase.s

# target to generate assembly for a file
interface/LovyanGFX/lgfx/v1/LGFXBase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/LGFXBase.cpp.s
.PHONY : interface/LovyanGFX/lgfx/v1/LGFXBase.cpp.s

interface/LovyanGFX/lgfx/v1/LGFX_Button.o: interface/LovyanGFX/lgfx/v1/LGFX_Button.cpp.o
.PHONY : interface/LovyanGFX/lgfx/v1/LGFX_Button.o

# target to build an object file
interface/LovyanGFX/lgfx/v1/LGFX_Button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/LGFX_Button.cpp.o
.PHONY : interface/LovyanGFX/lgfx/v1/LGFX_Button.cpp.o

interface/LovyanGFX/lgfx/v1/LGFX_Button.i: interface/LovyanGFX/lgfx/v1/LGFX_Button.cpp.i
.PHONY : interface/LovyanGFX/lgfx/v1/LGFX_Button.i

# target to preprocess a source file
interface/LovyanGFX/lgfx/v1/LGFX_Button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/LGFX_Button.cpp.i
.PHONY : interface/LovyanGFX/lgfx/v1/LGFX_Button.cpp.i

interface/LovyanGFX/lgfx/v1/LGFX_Button.s: interface/LovyanGFX/lgfx/v1/LGFX_Button.cpp.s
.PHONY : interface/LovyanGFX/lgfx/v1/LGFX_Button.s

# target to generate assembly for a file
interface/LovyanGFX/lgfx/v1/LGFX_Button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/LGFX_Button.cpp.s
.PHONY : interface/LovyanGFX/lgfx/v1/LGFX_Button.cpp.s

interface/LovyanGFX/lgfx/v1/LGFX_Sprite.o: interface/LovyanGFX/lgfx/v1/LGFX_Sprite.cpp.o
.PHONY : interface/LovyanGFX/lgfx/v1/LGFX_Sprite.o

# target to build an object file
interface/LovyanGFX/lgfx/v1/LGFX_Sprite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/LGFX_Sprite.cpp.o
.PHONY : interface/LovyanGFX/lgfx/v1/LGFX_Sprite.cpp.o

interface/LovyanGFX/lgfx/v1/LGFX_Sprite.i: interface/LovyanGFX/lgfx/v1/LGFX_Sprite.cpp.i
.PHONY : interface/LovyanGFX/lgfx/v1/LGFX_Sprite.i

# target to preprocess a source file
interface/LovyanGFX/lgfx/v1/LGFX_Sprite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/LGFX_Sprite.cpp.i
.PHONY : interface/LovyanGFX/lgfx/v1/LGFX_Sprite.cpp.i

interface/LovyanGFX/lgfx/v1/LGFX_Sprite.s: interface/LovyanGFX/lgfx/v1/LGFX_Sprite.cpp.s
.PHONY : interface/LovyanGFX/lgfx/v1/LGFX_Sprite.s

# target to generate assembly for a file
interface/LovyanGFX/lgfx/v1/LGFX_Sprite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/LGFX_Sprite.cpp.s
.PHONY : interface/LovyanGFX/lgfx/v1/LGFX_Sprite.cpp.s

interface/LovyanGFX/lgfx/v1/lgfx_fonts.o: interface/LovyanGFX/lgfx/v1/lgfx_fonts.cpp.o
.PHONY : interface/LovyanGFX/lgfx/v1/lgfx_fonts.o

# target to build an object file
interface/LovyanGFX/lgfx/v1/lgfx_fonts.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/lgfx_fonts.cpp.o
.PHONY : interface/LovyanGFX/lgfx/v1/lgfx_fonts.cpp.o

interface/LovyanGFX/lgfx/v1/lgfx_fonts.i: interface/LovyanGFX/lgfx/v1/lgfx_fonts.cpp.i
.PHONY : interface/LovyanGFX/lgfx/v1/lgfx_fonts.i

# target to preprocess a source file
interface/LovyanGFX/lgfx/v1/lgfx_fonts.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/lgfx_fonts.cpp.i
.PHONY : interface/LovyanGFX/lgfx/v1/lgfx_fonts.cpp.i

interface/LovyanGFX/lgfx/v1/lgfx_fonts.s: interface/LovyanGFX/lgfx/v1/lgfx_fonts.cpp.s
.PHONY : interface/LovyanGFX/lgfx/v1/lgfx_fonts.s

# target to generate assembly for a file
interface/LovyanGFX/lgfx/v1/lgfx_fonts.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/lgfx_fonts.cpp.s
.PHONY : interface/LovyanGFX/lgfx/v1/lgfx_fonts.cpp.s

interface/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.o: interface/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.cpp.o
.PHONY : interface/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.o

# target to build an object file
interface/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.cpp.o
.PHONY : interface/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.cpp.o

interface/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.i: interface/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.cpp.i
.PHONY : interface/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.i

# target to preprocess a source file
interface/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.cpp.i
.PHONY : interface/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.cpp.i

interface/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.s: interface/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.cpp.s
.PHONY : interface/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.s

# target to generate assembly for a file
interface/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.cpp.s
.PHONY : interface/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.cpp.s

interface/LovyanGFX/lgfx/v1/misc/SpriteBuffer.o: interface/LovyanGFX/lgfx/v1/misc/SpriteBuffer.cpp.o
.PHONY : interface/LovyanGFX/lgfx/v1/misc/SpriteBuffer.o

# target to build an object file
interface/LovyanGFX/lgfx/v1/misc/SpriteBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/misc/SpriteBuffer.cpp.o
.PHONY : interface/LovyanGFX/lgfx/v1/misc/SpriteBuffer.cpp.o

interface/LovyanGFX/lgfx/v1/misc/SpriteBuffer.i: interface/LovyanGFX/lgfx/v1/misc/SpriteBuffer.cpp.i
.PHONY : interface/LovyanGFX/lgfx/v1/misc/SpriteBuffer.i

# target to preprocess a source file
interface/LovyanGFX/lgfx/v1/misc/SpriteBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/misc/SpriteBuffer.cpp.i
.PHONY : interface/LovyanGFX/lgfx/v1/misc/SpriteBuffer.cpp.i

interface/LovyanGFX/lgfx/v1/misc/SpriteBuffer.s: interface/LovyanGFX/lgfx/v1/misc/SpriteBuffer.cpp.s
.PHONY : interface/LovyanGFX/lgfx/v1/misc/SpriteBuffer.s

# target to generate assembly for a file
interface/LovyanGFX/lgfx/v1/misc/SpriteBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/misc/SpriteBuffer.cpp.s
.PHONY : interface/LovyanGFX/lgfx/v1/misc/SpriteBuffer.cpp.s

interface/LovyanGFX/lgfx/v1/misc/common_function.o: interface/LovyanGFX/lgfx/v1/misc/common_function.cpp.o
.PHONY : interface/LovyanGFX/lgfx/v1/misc/common_function.o

# target to build an object file
interface/LovyanGFX/lgfx/v1/misc/common_function.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/misc/common_function.cpp.o
.PHONY : interface/LovyanGFX/lgfx/v1/misc/common_function.cpp.o

interface/LovyanGFX/lgfx/v1/misc/common_function.i: interface/LovyanGFX/lgfx/v1/misc/common_function.cpp.i
.PHONY : interface/LovyanGFX/lgfx/v1/misc/common_function.i

# target to preprocess a source file
interface/LovyanGFX/lgfx/v1/misc/common_function.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/misc/common_function.cpp.i
.PHONY : interface/LovyanGFX/lgfx/v1/misc/common_function.cpp.i

interface/LovyanGFX/lgfx/v1/misc/common_function.s: interface/LovyanGFX/lgfx/v1/misc/common_function.cpp.s
.PHONY : interface/LovyanGFX/lgfx/v1/misc/common_function.s

# target to generate assembly for a file
interface/LovyanGFX/lgfx/v1/misc/common_function.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/misc/common_function.cpp.s
.PHONY : interface/LovyanGFX/lgfx/v1/misc/common_function.cpp.s

interface/LovyanGFX/lgfx/v1/misc/pixelcopy.o: interface/LovyanGFX/lgfx/v1/misc/pixelcopy.cpp.o
.PHONY : interface/LovyanGFX/lgfx/v1/misc/pixelcopy.o

# target to build an object file
interface/LovyanGFX/lgfx/v1/misc/pixelcopy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/misc/pixelcopy.cpp.o
.PHONY : interface/LovyanGFX/lgfx/v1/misc/pixelcopy.cpp.o

interface/LovyanGFX/lgfx/v1/misc/pixelcopy.i: interface/LovyanGFX/lgfx/v1/misc/pixelcopy.cpp.i
.PHONY : interface/LovyanGFX/lgfx/v1/misc/pixelcopy.i

# target to preprocess a source file
interface/LovyanGFX/lgfx/v1/misc/pixelcopy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/misc/pixelcopy.cpp.i
.PHONY : interface/LovyanGFX/lgfx/v1/misc/pixelcopy.cpp.i

interface/LovyanGFX/lgfx/v1/misc/pixelcopy.s: interface/LovyanGFX/lgfx/v1/misc/pixelcopy.cpp.s
.PHONY : interface/LovyanGFX/lgfx/v1/misc/pixelcopy.s

# target to generate assembly for a file
interface/LovyanGFX/lgfx/v1/misc/pixelcopy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/misc/pixelcopy.cpp.s
.PHONY : interface/LovyanGFX/lgfx/v1/misc/pixelcopy.cpp.s

interface/LovyanGFX/lgfx/v1/panel/Panel_Device.o: interface/LovyanGFX/lgfx/v1/panel/Panel_Device.cpp.o
.PHONY : interface/LovyanGFX/lgfx/v1/panel/Panel_Device.o

# target to build an object file
interface/LovyanGFX/lgfx/v1/panel/Panel_Device.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/panel/Panel_Device.cpp.o
.PHONY : interface/LovyanGFX/lgfx/v1/panel/Panel_Device.cpp.o

interface/LovyanGFX/lgfx/v1/panel/Panel_Device.i: interface/LovyanGFX/lgfx/v1/panel/Panel_Device.cpp.i
.PHONY : interface/LovyanGFX/lgfx/v1/panel/Panel_Device.i

# target to preprocess a source file
interface/LovyanGFX/lgfx/v1/panel/Panel_Device.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/panel/Panel_Device.cpp.i
.PHONY : interface/LovyanGFX/lgfx/v1/panel/Panel_Device.cpp.i

interface/LovyanGFX/lgfx/v1/panel/Panel_Device.s: interface/LovyanGFX/lgfx/v1/panel/Panel_Device.cpp.s
.PHONY : interface/LovyanGFX/lgfx/v1/panel/Panel_Device.s

# target to generate assembly for a file
interface/LovyanGFX/lgfx/v1/panel/Panel_Device.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/panel/Panel_Device.cpp.s
.PHONY : interface/LovyanGFX/lgfx/v1/panel/Panel_Device.cpp.s

interface/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.o: interface/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.cpp.o
.PHONY : interface/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.o

# target to build an object file
interface/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.cpp.o
.PHONY : interface/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.cpp.o

interface/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.i: interface/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.cpp.i
.PHONY : interface/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.i

# target to preprocess a source file
interface/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.cpp.i
.PHONY : interface/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.cpp.i

interface/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.s: interface/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.cpp.s
.PHONY : interface/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.s

# target to generate assembly for a file
interface/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.cpp.s
.PHONY : interface/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.cpp.s

interface/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.o: interface/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.cpp.o
.PHONY : interface/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.o

# target to build an object file
interface/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.cpp.o
.PHONY : interface/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.cpp.o

interface/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.i: interface/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.cpp.i
.PHONY : interface/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.i

# target to preprocess a source file
interface/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.cpp.i
.PHONY : interface/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.cpp.i

interface/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.s: interface/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.cpp.s
.PHONY : interface/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.s

# target to generate assembly for a file
interface/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.cpp.s
.PHONY : interface/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.cpp.s

interface/LovyanGFX/lgfx/v1/platforms/sdl/common.o: interface/LovyanGFX/lgfx/v1/platforms/sdl/common.cpp.o
.PHONY : interface/LovyanGFX/lgfx/v1/platforms/sdl/common.o

# target to build an object file
interface/LovyanGFX/lgfx/v1/platforms/sdl/common.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/platforms/sdl/common.cpp.o
.PHONY : interface/LovyanGFX/lgfx/v1/platforms/sdl/common.cpp.o

interface/LovyanGFX/lgfx/v1/platforms/sdl/common.i: interface/LovyanGFX/lgfx/v1/platforms/sdl/common.cpp.i
.PHONY : interface/LovyanGFX/lgfx/v1/platforms/sdl/common.i

# target to preprocess a source file
interface/LovyanGFX/lgfx/v1/platforms/sdl/common.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/platforms/sdl/common.cpp.i
.PHONY : interface/LovyanGFX/lgfx/v1/platforms/sdl/common.cpp.i

interface/LovyanGFX/lgfx/v1/platforms/sdl/common.s: interface/LovyanGFX/lgfx/v1/platforms/sdl/common.cpp.s
.PHONY : interface/LovyanGFX/lgfx/v1/platforms/sdl/common.s

# target to generate assembly for a file
interface/LovyanGFX/lgfx/v1/platforms/sdl/common.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/interface/LovyanGFX/lgfx/v1/platforms/sdl/common.cpp.s
.PHONY : interface/LovyanGFX/lgfx/v1/platforms/sdl/common.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... PaxOS8"
	@echo "... interface/LovyanGFX/LGFX_SDL.o"
	@echo "... interface/LovyanGFX/LGFX_SDL.i"
	@echo "... interface/LovyanGFX/LGFX_SDL.s"
	@echo "... interface/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.o"
	@echo "... interface/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.i"
	@echo "... interface/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.s"
	@echo "... interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.o"
	@echo "... interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.i"
	@echo "... interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.s"
	@echo "... interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.o"
	@echo "... interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.i"
	@echo "... interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.s"
	@echo "... interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.o"
	@echo "... interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.i"
	@echo "... interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.s"
	@echo "... interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.o"
	@echo "... interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.i"
	@echo "... interface/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.s"
	@echo "... interface/LovyanGFX/lgfx/utility/lgfx_pngle.o"
	@echo "... interface/LovyanGFX/lgfx/utility/lgfx_pngle.i"
	@echo "... interface/LovyanGFX/lgfx/utility/lgfx_pngle.s"
	@echo "... interface/LovyanGFX/lgfx/utility/lgfx_qoi.o"
	@echo "... interface/LovyanGFX/lgfx/utility/lgfx_qoi.i"
	@echo "... interface/LovyanGFX/lgfx/utility/lgfx_qoi.s"
	@echo "... interface/LovyanGFX/lgfx/utility/lgfx_qrcode.o"
	@echo "... interface/LovyanGFX/lgfx/utility/lgfx_qrcode.i"
	@echo "... interface/LovyanGFX/lgfx/utility/lgfx_qrcode.s"
	@echo "... interface/LovyanGFX/lgfx/utility/lgfx_tjpgd.o"
	@echo "... interface/LovyanGFX/lgfx/utility/lgfx_tjpgd.i"
	@echo "... interface/LovyanGFX/lgfx/utility/lgfx_tjpgd.s"
	@echo "... interface/LovyanGFX/lgfx/utility/miniz.o"
	@echo "... interface/LovyanGFX/lgfx/utility/miniz.i"
	@echo "... interface/LovyanGFX/lgfx/utility/miniz.s"
	@echo "... interface/LovyanGFX/lgfx/v1/LGFXBase.o"
	@echo "... interface/LovyanGFX/lgfx/v1/LGFXBase.i"
	@echo "... interface/LovyanGFX/lgfx/v1/LGFXBase.s"
	@echo "... interface/LovyanGFX/lgfx/v1/LGFX_Button.o"
	@echo "... interface/LovyanGFX/lgfx/v1/LGFX_Button.i"
	@echo "... interface/LovyanGFX/lgfx/v1/LGFX_Button.s"
	@echo "... interface/LovyanGFX/lgfx/v1/LGFX_Sprite.o"
	@echo "... interface/LovyanGFX/lgfx/v1/LGFX_Sprite.i"
	@echo "... interface/LovyanGFX/lgfx/v1/LGFX_Sprite.s"
	@echo "... interface/LovyanGFX/lgfx/v1/lgfx_fonts.o"
	@echo "... interface/LovyanGFX/lgfx/v1/lgfx_fonts.i"
	@echo "... interface/LovyanGFX/lgfx/v1/lgfx_fonts.s"
	@echo "... interface/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.o"
	@echo "... interface/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.i"
	@echo "... interface/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.s"
	@echo "... interface/LovyanGFX/lgfx/v1/misc/SpriteBuffer.o"
	@echo "... interface/LovyanGFX/lgfx/v1/misc/SpriteBuffer.i"
	@echo "... interface/LovyanGFX/lgfx/v1/misc/SpriteBuffer.s"
	@echo "... interface/LovyanGFX/lgfx/v1/misc/common_function.o"
	@echo "... interface/LovyanGFX/lgfx/v1/misc/common_function.i"
	@echo "... interface/LovyanGFX/lgfx/v1/misc/common_function.s"
	@echo "... interface/LovyanGFX/lgfx/v1/misc/pixelcopy.o"
	@echo "... interface/LovyanGFX/lgfx/v1/misc/pixelcopy.i"
	@echo "... interface/LovyanGFX/lgfx/v1/misc/pixelcopy.s"
	@echo "... interface/LovyanGFX/lgfx/v1/panel/Panel_Device.o"
	@echo "... interface/LovyanGFX/lgfx/v1/panel/Panel_Device.i"
	@echo "... interface/LovyanGFX/lgfx/v1/panel/Panel_Device.s"
	@echo "... interface/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.o"
	@echo "... interface/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.i"
	@echo "... interface/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.s"
	@echo "... interface/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.o"
	@echo "... interface/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.i"
	@echo "... interface/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.s"
	@echo "... interface/LovyanGFX/lgfx/v1/platforms/sdl/common.o"
	@echo "... interface/LovyanGFX/lgfx/v1/platforms/sdl/common.i"
	@echo "... interface/LovyanGFX/lgfx/v1/platforms/sdl/common.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/gabriel/Bureau/paxos_8/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

