# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gabriel/Bureau/paxos_8_re

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gabriel/Bureau/paxos_8_re

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gabriel/Bureau/paxos_8_re/CMakeFiles /home/gabriel/Bureau/paxos_8_re//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gabriel/Bureau/paxos_8_re/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/gabriel/Bureau/paxos_8_re/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PaxOS8

# Build rule for target.
PaxOS8: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PaxOS8
.PHONY : PaxOS8

# fast build rule for target.
PaxOS8/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/build
.PHONY : PaxOS8/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/main.cpp.s
.PHONY : main.cpp.s

src/apps/calcul/calcul.o: src/apps/calcul/calcul.cpp.o
.PHONY : src/apps/calcul/calcul.o

# target to build an object file
src/apps/calcul/calcul.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/apps/calcul/calcul.cpp.o
.PHONY : src/apps/calcul/calcul.cpp.o

src/apps/calcul/calcul.i: src/apps/calcul/calcul.cpp.i
.PHONY : src/apps/calcul/calcul.i

# target to preprocess a source file
src/apps/calcul/calcul.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/apps/calcul/calcul.cpp.i
.PHONY : src/apps/calcul/calcul.cpp.i

src/apps/calcul/calcul.s: src/apps/calcul/calcul.cpp.s
.PHONY : src/apps/calcul/calcul.s

# target to generate assembly for a file
src/apps/calcul/calcul.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/apps/calcul/calcul.cpp.s
.PHONY : src/apps/calcul/calcul.cpp.s

src/apps/contact/contact.o: src/apps/contact/contact.cpp.o
.PHONY : src/apps/contact/contact.o

# target to build an object file
src/apps/contact/contact.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/apps/contact/contact.cpp.o
.PHONY : src/apps/contact/contact.cpp.o

src/apps/contact/contact.i: src/apps/contact/contact.cpp.i
.PHONY : src/apps/contact/contact.i

# target to preprocess a source file
src/apps/contact/contact.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/apps/contact/contact.cpp.i
.PHONY : src/apps/contact/contact.cpp.i

src/apps/contact/contact.s: src/apps/contact/contact.cpp.s
.PHONY : src/apps/contact/contact.s

# target to generate assembly for a file
src/apps/contact/contact.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/apps/contact/contact.cpp.s
.PHONY : src/apps/contact/contact.cpp.s

src/apps/launcher.o: src/apps/launcher.cpp.o
.PHONY : src/apps/launcher.o

# target to build an object file
src/apps/launcher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/apps/launcher.cpp.o
.PHONY : src/apps/launcher.cpp.o

src/apps/launcher.i: src/apps/launcher.cpp.i
.PHONY : src/apps/launcher.i

# target to preprocess a source file
src/apps/launcher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/apps/launcher.cpp.i
.PHONY : src/apps/launcher.cpp.i

src/apps/launcher.s: src/apps/launcher.cpp.s
.PHONY : src/apps/launcher.s

# target to generate assembly for a file
src/apps/launcher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/apps/launcher.cpp.s
.PHONY : src/apps/launcher.cpp.s

src/apps/message/message.o: src/apps/message/message.cpp.o
.PHONY : src/apps/message/message.o

# target to build an object file
src/apps/message/message.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/apps/message/message.cpp.o
.PHONY : src/apps/message/message.cpp.o

src/apps/message/message.i: src/apps/message/message.cpp.i
.PHONY : src/apps/message/message.i

# target to preprocess a source file
src/apps/message/message.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/apps/message/message.cpp.i
.PHONY : src/apps/message/message.cpp.i

src/apps/message/message.s: src/apps/message/message.cpp.s
.PHONY : src/apps/message/message.s

# target to generate assembly for a file
src/apps/message/message.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/apps/message/message.cpp.s
.PHONY : src/apps/message/message.cpp.s

src/apps/phone/phone.o: src/apps/phone/phone.cpp.o
.PHONY : src/apps/phone/phone.o

# target to build an object file
src/apps/phone/phone.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/apps/phone/phone.cpp.o
.PHONY : src/apps/phone/phone.cpp.o

src/apps/phone/phone.i: src/apps/phone/phone.cpp.i
.PHONY : src/apps/phone/phone.i

# target to preprocess a source file
src/apps/phone/phone.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/apps/phone/phone.cpp.i
.PHONY : src/apps/phone/phone.cpp.i

src/apps/phone/phone.s: src/apps/phone/phone.cpp.s
.PHONY : src/apps/phone/phone.s

# target to generate assembly for a file
src/apps/phone/phone.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/apps/phone/phone.cpp.s
.PHONY : src/apps/phone/phone.cpp.s

src/apps/settings/settings.o: src/apps/settings/settings.cpp.o
.PHONY : src/apps/settings/settings.o

# target to build an object file
src/apps/settings/settings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/apps/settings/settings.cpp.o
.PHONY : src/apps/settings/settings.cpp.o

src/apps/settings/settings.i: src/apps/settings/settings.cpp.i
.PHONY : src/apps/settings/settings.i

# target to preprocess a source file
src/apps/settings/settings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/apps/settings/settings.cpp.i
.PHONY : src/apps/settings/settings.cpp.i

src/apps/settings/settings.s: src/apps/settings/settings.cpp.s
.PHONY : src/apps/settings/settings.s

# target to generate assembly for a file
src/apps/settings/settings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/apps/settings/settings.cpp.s
.PHONY : src/apps/settings/settings.cpp.s

src/drivers/GSM/Sim800L/sim.o: src/drivers/GSM/Sim800L/sim.cpp.o
.PHONY : src/drivers/GSM/Sim800L/sim.o

# target to build an object file
src/drivers/GSM/Sim800L/sim.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/GSM/Sim800L/sim.cpp.o
.PHONY : src/drivers/GSM/Sim800L/sim.cpp.o

src/drivers/GSM/Sim800L/sim.i: src/drivers/GSM/Sim800L/sim.cpp.i
.PHONY : src/drivers/GSM/Sim800L/sim.i

# target to preprocess a source file
src/drivers/GSM/Sim800L/sim.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/GSM/Sim800L/sim.cpp.i
.PHONY : src/drivers/GSM/Sim800L/sim.cpp.i

src/drivers/GSM/Sim800L/sim.s: src/drivers/GSM/Sim800L/sim.cpp.s
.PHONY : src/drivers/GSM/Sim800L/sim.s

# target to generate assembly for a file
src/drivers/GSM/Sim800L/sim.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/GSM/Sim800L/sim.cpp.s
.PHONY : src/drivers/GSM/Sim800L/sim.cpp.s

src/drivers/button/button.o: src/drivers/button/button.cpp.o
.PHONY : src/drivers/button/button.o

# target to build an object file
src/drivers/button/button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/button/button.cpp.o
.PHONY : src/drivers/button/button.cpp.o

src/drivers/button/button.i: src/drivers/button/button.cpp.i
.PHONY : src/drivers/button/button.i

# target to preprocess a source file
src/drivers/button/button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/button/button.cpp.i
.PHONY : src/drivers/button/button.cpp.i

src/drivers/button/button.s: src/drivers/button/button.cpp.s
.PHONY : src/drivers/button/button.s

# target to generate assembly for a file
src/drivers/button/button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/button/button.cpp.s
.PHONY : src/drivers/button/button.cpp.s

src/drivers/screen/LovyanGFX/LGFX_SDL.o: src/drivers/screen/LovyanGFX/LGFX_SDL.cpp.o
.PHONY : src/drivers/screen/LovyanGFX/LGFX_SDL.o

# target to build an object file
src/drivers/screen/LovyanGFX/LGFX_SDL.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/LGFX_SDL.cpp.o
.PHONY : src/drivers/screen/LovyanGFX/LGFX_SDL.cpp.o

src/drivers/screen/LovyanGFX/LGFX_SDL.i: src/drivers/screen/LovyanGFX/LGFX_SDL.cpp.i
.PHONY : src/drivers/screen/LovyanGFX/LGFX_SDL.i

# target to preprocess a source file
src/drivers/screen/LovyanGFX/LGFX_SDL.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/LGFX_SDL.cpp.i
.PHONY : src/drivers/screen/LovyanGFX/LGFX_SDL.cpp.i

src/drivers/screen/LovyanGFX/LGFX_SDL.s: src/drivers/screen/LovyanGFX/LGFX_SDL.cpp.s
.PHONY : src/drivers/screen/LovyanGFX/LGFX_SDL.s

# target to generate assembly for a file
src/drivers/screen/LovyanGFX/LGFX_SDL.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/LGFX_SDL.cpp.s
.PHONY : src/drivers/screen/LovyanGFX/LGFX_SDL.cpp.s

src/drivers/screen/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.o: src/drivers/screen/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.c.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.o

# target to build an object file
src/drivers/screen/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.c.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.c.o

src/drivers/screen/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.i: src/drivers/screen/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.c.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.i

# target to preprocess a source file
src/drivers/screen/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.c.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.c.i

src/drivers/screen/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.s: src/drivers/screen/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.c.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.s

# target to generate assembly for a file
src/drivers/screen/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.c.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.c.s

src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.o: src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.c.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.o

# target to build an object file
src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.c.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.c.o

src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.i: src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.c.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.i

# target to preprocess a source file
src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.c.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.c.i

src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.s: src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.c.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.s

# target to generate assembly for a file
src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.c.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.c.s

src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.o: src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.c.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.o

# target to build an object file
src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.c.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.c.o

src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.i: src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.c.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.i

# target to preprocess a source file
src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.c.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.c.i

src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.s: src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.c.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.s

# target to generate assembly for a file
src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.c.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.c.s

src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.o: src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.c.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.o

# target to build an object file
src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.c.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.c.o

src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.i: src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.c.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.i

# target to preprocess a source file
src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.c.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.c.i

src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.s: src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.c.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.s

# target to generate assembly for a file
src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.c.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.c.s

src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.o: src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.c.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.o

# target to build an object file
src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.c.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.c.o

src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.i: src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.c.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.i

# target to preprocess a source file
src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.c.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.c.i

src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.s: src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.c.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.s

# target to generate assembly for a file
src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.c.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.c.s

src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_pngle.o: src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_pngle.c.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_pngle.o

# target to build an object file
src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_pngle.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_pngle.c.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_pngle.c.o

src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_pngle.i: src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_pngle.c.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_pngle.i

# target to preprocess a source file
src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_pngle.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_pngle.c.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_pngle.c.i

src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_pngle.s: src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_pngle.c.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_pngle.s

# target to generate assembly for a file
src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_pngle.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_pngle.c.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_pngle.c.s

src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qoi.o: src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qoi.c.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qoi.o

# target to build an object file
src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qoi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qoi.c.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qoi.c.o

src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qoi.i: src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qoi.c.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qoi.i

# target to preprocess a source file
src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qoi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qoi.c.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qoi.c.i

src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qoi.s: src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qoi.c.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qoi.s

# target to generate assembly for a file
src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qoi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qoi.c.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qoi.c.s

src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qrcode.o: src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qrcode.c.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qrcode.o

# target to build an object file
src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qrcode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qrcode.c.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qrcode.c.o

src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qrcode.i: src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qrcode.c.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qrcode.i

# target to preprocess a source file
src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qrcode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qrcode.c.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qrcode.c.i

src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qrcode.s: src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qrcode.c.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qrcode.s

# target to generate assembly for a file
src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qrcode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qrcode.c.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qrcode.c.s

src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_tjpgd.o: src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_tjpgd.c.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_tjpgd.o

# target to build an object file
src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_tjpgd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_tjpgd.c.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_tjpgd.c.o

src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_tjpgd.i: src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_tjpgd.c.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_tjpgd.i

# target to preprocess a source file
src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_tjpgd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_tjpgd.c.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_tjpgd.c.i

src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_tjpgd.s: src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_tjpgd.c.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_tjpgd.s

# target to generate assembly for a file
src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_tjpgd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_tjpgd.c.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_tjpgd.c.s

src/drivers/screen/LovyanGFX/lgfx/utility/miniz.o: src/drivers/screen/LovyanGFX/lgfx/utility/miniz.c.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/utility/miniz.o

# target to build an object file
src/drivers/screen/LovyanGFX/lgfx/utility/miniz.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/utility/miniz.c.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/utility/miniz.c.o

src/drivers/screen/LovyanGFX/lgfx/utility/miniz.i: src/drivers/screen/LovyanGFX/lgfx/utility/miniz.c.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/utility/miniz.i

# target to preprocess a source file
src/drivers/screen/LovyanGFX/lgfx/utility/miniz.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/utility/miniz.c.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/utility/miniz.c.i

src/drivers/screen/LovyanGFX/lgfx/utility/miniz.s: src/drivers/screen/LovyanGFX/lgfx/utility/miniz.c.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/utility/miniz.s

# target to generate assembly for a file
src/drivers/screen/LovyanGFX/lgfx/utility/miniz.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/utility/miniz.c.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/utility/miniz.c.s

src/drivers/screen/LovyanGFX/lgfx/v1/LGFXBase.o: src/drivers/screen/LovyanGFX/lgfx/v1/LGFXBase.cpp.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/LGFXBase.o

# target to build an object file
src/drivers/screen/LovyanGFX/lgfx/v1/LGFXBase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/LGFXBase.cpp.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/LGFXBase.cpp.o

src/drivers/screen/LovyanGFX/lgfx/v1/LGFXBase.i: src/drivers/screen/LovyanGFX/lgfx/v1/LGFXBase.cpp.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/LGFXBase.i

# target to preprocess a source file
src/drivers/screen/LovyanGFX/lgfx/v1/LGFXBase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/LGFXBase.cpp.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/LGFXBase.cpp.i

src/drivers/screen/LovyanGFX/lgfx/v1/LGFXBase.s: src/drivers/screen/LovyanGFX/lgfx/v1/LGFXBase.cpp.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/LGFXBase.s

# target to generate assembly for a file
src/drivers/screen/LovyanGFX/lgfx/v1/LGFXBase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/LGFXBase.cpp.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/LGFXBase.cpp.s

src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Button.o: src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Button.cpp.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Button.o

# target to build an object file
src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Button.cpp.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Button.cpp.o

src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Button.i: src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Button.cpp.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Button.i

# target to preprocess a source file
src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Button.cpp.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Button.cpp.i

src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Button.s: src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Button.cpp.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Button.s

# target to generate assembly for a file
src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Button.cpp.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Button.cpp.s

src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Sprite.o: src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Sprite.cpp.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Sprite.o

# target to build an object file
src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Sprite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Sprite.cpp.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Sprite.cpp.o

src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Sprite.i: src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Sprite.cpp.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Sprite.i

# target to preprocess a source file
src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Sprite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Sprite.cpp.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Sprite.cpp.i

src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Sprite.s: src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Sprite.cpp.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Sprite.s

# target to generate assembly for a file
src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Sprite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Sprite.cpp.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Sprite.cpp.s

src/drivers/screen/LovyanGFX/lgfx/v1/lgfx_fonts.o: src/drivers/screen/LovyanGFX/lgfx/v1/lgfx_fonts.cpp.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/lgfx_fonts.o

# target to build an object file
src/drivers/screen/LovyanGFX/lgfx/v1/lgfx_fonts.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/lgfx_fonts.cpp.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/lgfx_fonts.cpp.o

src/drivers/screen/LovyanGFX/lgfx/v1/lgfx_fonts.i: src/drivers/screen/LovyanGFX/lgfx/v1/lgfx_fonts.cpp.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/lgfx_fonts.i

# target to preprocess a source file
src/drivers/screen/LovyanGFX/lgfx/v1/lgfx_fonts.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/lgfx_fonts.cpp.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/lgfx_fonts.cpp.i

src/drivers/screen/LovyanGFX/lgfx/v1/lgfx_fonts.s: src/drivers/screen/LovyanGFX/lgfx/v1/lgfx_fonts.cpp.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/lgfx_fonts.s

# target to generate assembly for a file
src/drivers/screen/LovyanGFX/lgfx/v1/lgfx_fonts.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/lgfx_fonts.cpp.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/lgfx_fonts.cpp.s

src/drivers/screen/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.o: src/drivers/screen/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.cpp.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.o

# target to build an object file
src/drivers/screen/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.cpp.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.cpp.o

src/drivers/screen/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.i: src/drivers/screen/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.cpp.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.i

# target to preprocess a source file
src/drivers/screen/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.cpp.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.cpp.i

src/drivers/screen/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.s: src/drivers/screen/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.cpp.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.s

# target to generate assembly for a file
src/drivers/screen/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.cpp.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.cpp.s

src/drivers/screen/LovyanGFX/lgfx/v1/misc/SpriteBuffer.o: src/drivers/screen/LovyanGFX/lgfx/v1/misc/SpriteBuffer.cpp.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/misc/SpriteBuffer.o

# target to build an object file
src/drivers/screen/LovyanGFX/lgfx/v1/misc/SpriteBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/misc/SpriteBuffer.cpp.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/misc/SpriteBuffer.cpp.o

src/drivers/screen/LovyanGFX/lgfx/v1/misc/SpriteBuffer.i: src/drivers/screen/LovyanGFX/lgfx/v1/misc/SpriteBuffer.cpp.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/misc/SpriteBuffer.i

# target to preprocess a source file
src/drivers/screen/LovyanGFX/lgfx/v1/misc/SpriteBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/misc/SpriteBuffer.cpp.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/misc/SpriteBuffer.cpp.i

src/drivers/screen/LovyanGFX/lgfx/v1/misc/SpriteBuffer.s: src/drivers/screen/LovyanGFX/lgfx/v1/misc/SpriteBuffer.cpp.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/misc/SpriteBuffer.s

# target to generate assembly for a file
src/drivers/screen/LovyanGFX/lgfx/v1/misc/SpriteBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/misc/SpriteBuffer.cpp.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/misc/SpriteBuffer.cpp.s

src/drivers/screen/LovyanGFX/lgfx/v1/misc/common_function.o: src/drivers/screen/LovyanGFX/lgfx/v1/misc/common_function.cpp.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/misc/common_function.o

# target to build an object file
src/drivers/screen/LovyanGFX/lgfx/v1/misc/common_function.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/misc/common_function.cpp.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/misc/common_function.cpp.o

src/drivers/screen/LovyanGFX/lgfx/v1/misc/common_function.i: src/drivers/screen/LovyanGFX/lgfx/v1/misc/common_function.cpp.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/misc/common_function.i

# target to preprocess a source file
src/drivers/screen/LovyanGFX/lgfx/v1/misc/common_function.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/misc/common_function.cpp.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/misc/common_function.cpp.i

src/drivers/screen/LovyanGFX/lgfx/v1/misc/common_function.s: src/drivers/screen/LovyanGFX/lgfx/v1/misc/common_function.cpp.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/misc/common_function.s

# target to generate assembly for a file
src/drivers/screen/LovyanGFX/lgfx/v1/misc/common_function.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/misc/common_function.cpp.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/misc/common_function.cpp.s

src/drivers/screen/LovyanGFX/lgfx/v1/misc/pixelcopy.o: src/drivers/screen/LovyanGFX/lgfx/v1/misc/pixelcopy.cpp.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/misc/pixelcopy.o

# target to build an object file
src/drivers/screen/LovyanGFX/lgfx/v1/misc/pixelcopy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/misc/pixelcopy.cpp.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/misc/pixelcopy.cpp.o

src/drivers/screen/LovyanGFX/lgfx/v1/misc/pixelcopy.i: src/drivers/screen/LovyanGFX/lgfx/v1/misc/pixelcopy.cpp.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/misc/pixelcopy.i

# target to preprocess a source file
src/drivers/screen/LovyanGFX/lgfx/v1/misc/pixelcopy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/misc/pixelcopy.cpp.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/misc/pixelcopy.cpp.i

src/drivers/screen/LovyanGFX/lgfx/v1/misc/pixelcopy.s: src/drivers/screen/LovyanGFX/lgfx/v1/misc/pixelcopy.cpp.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/misc/pixelcopy.s

# target to generate assembly for a file
src/drivers/screen/LovyanGFX/lgfx/v1/misc/pixelcopy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/misc/pixelcopy.cpp.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/misc/pixelcopy.cpp.s

src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_Device.o: src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_Device.cpp.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_Device.o

# target to build an object file
src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_Device.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_Device.cpp.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_Device.cpp.o

src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_Device.i: src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_Device.cpp.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_Device.i

# target to preprocess a source file
src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_Device.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_Device.cpp.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_Device.cpp.i

src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_Device.s: src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_Device.cpp.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_Device.s

# target to generate assembly for a file
src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_Device.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_Device.cpp.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_Device.cpp.s

src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.o: src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.cpp.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.o

# target to build an object file
src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.cpp.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.cpp.o

src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.i: src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.cpp.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.i

# target to preprocess a source file
src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.cpp.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.cpp.i

src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.s: src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.cpp.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.s

# target to generate assembly for a file
src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.cpp.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.cpp.s

src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.o: src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.cpp.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.o

# target to build an object file
src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.cpp.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.cpp.o

src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.i: src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.cpp.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.i

# target to preprocess a source file
src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.cpp.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.cpp.i

src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.s: src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.cpp.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.s

# target to generate assembly for a file
src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.cpp.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.cpp.s

src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/common.o: src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/common.cpp.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/common.o

# target to build an object file
src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/common.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/common.cpp.o
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/common.cpp.o

src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/common.i: src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/common.cpp.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/common.i

# target to preprocess a source file
src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/common.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/common.cpp.i
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/common.cpp.i

src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/common.s: src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/common.cpp.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/common.s

# target to generate assembly for a file
src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/common.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/common.cpp.s
.PHONY : src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/common.cpp.s

src/drivers/storage/storage/storage.o: src/drivers/storage/storage/storage.cpp.o
.PHONY : src/drivers/storage/storage/storage.o

# target to build an object file
src/drivers/storage/storage/storage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/storage/storage/storage.cpp.o
.PHONY : src/drivers/storage/storage/storage.cpp.o

src/drivers/storage/storage/storage.i: src/drivers/storage/storage/storage.cpp.i
.PHONY : src/drivers/storage/storage/storage.i

# target to preprocess a source file
src/drivers/storage/storage/storage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/storage/storage/storage.cpp.i
.PHONY : src/drivers/storage/storage/storage.cpp.i

src/drivers/storage/storage/storage.s: src/drivers/storage/storage/storage.cpp.s
.PHONY : src/drivers/storage/storage/storage.s

# target to generate assembly for a file
src/drivers/storage/storage/storage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/drivers/storage/storage/storage.cpp.s
.PHONY : src/drivers/storage/storage/storage.cpp.s

src/modules/lua/lua.o: src/modules/lua/lua.cpp.o
.PHONY : src/modules/lua/lua.o

# target to build an object file
src/modules/lua/lua.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/modules/lua/lua.cpp.o
.PHONY : src/modules/lua/lua.cpp.o

src/modules/lua/lua.i: src/modules/lua/lua.cpp.i
.PHONY : src/modules/lua/lua.i

# target to preprocess a source file
src/modules/lua/lua.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/modules/lua/lua.cpp.i
.PHONY : src/modules/lua/lua.cpp.i

src/modules/lua/lua.s: src/modules/lua/lua.cpp.s
.PHONY : src/modules/lua/lua.s

# target to generate assembly for a file
src/modules/lua/lua.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/modules/lua/lua.cpp.s
.PHONY : src/modules/lua/lua.cpp.s

src/modules/shell/shell.o: src/modules/shell/shell.cpp.o
.PHONY : src/modules/shell/shell.o

# target to build an object file
src/modules/shell/shell.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/modules/shell/shell.cpp.o
.PHONY : src/modules/shell/shell.cpp.o

src/modules/shell/shell.i: src/modules/shell/shell.cpp.i
.PHONY : src/modules/shell/shell.i

# target to preprocess a source file
src/modules/shell/shell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/modules/shell/shell.cpp.i
.PHONY : src/modules/shell/shell.cpp.i

src/modules/shell/shell.s: src/modules/shell/shell.cpp.s
.PHONY : src/modules/shell/shell.s

# target to generate assembly for a file
src/modules/shell/shell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/modules/shell/shell.cpp.s
.PHONY : src/modules/shell/shell.cpp.s

src/modules/widgets/gui.o: src/modules/widgets/gui.cpp.o
.PHONY : src/modules/widgets/gui.o

# target to build an object file
src/modules/widgets/gui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/modules/widgets/gui.cpp.o
.PHONY : src/modules/widgets/gui.cpp.o

src/modules/widgets/gui.i: src/modules/widgets/gui.cpp.i
.PHONY : src/modules/widgets/gui.i

# target to preprocess a source file
src/modules/widgets/gui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/modules/widgets/gui.cpp.i
.PHONY : src/modules/widgets/gui.cpp.i

src/modules/widgets/gui.s: src/modules/widgets/gui.cpp.s
.PHONY : src/modules/widgets/gui.s

# target to generate assembly for a file
src/modules/widgets/gui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/modules/widgets/gui.cpp.s
.PHONY : src/modules/widgets/gui.cpp.s

src/modules/widgets/gui/button.o: src/modules/widgets/gui/button.cpp.o
.PHONY : src/modules/widgets/gui/button.o

# target to build an object file
src/modules/widgets/gui/button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/modules/widgets/gui/button.cpp.o
.PHONY : src/modules/widgets/gui/button.cpp.o

src/modules/widgets/gui/button.i: src/modules/widgets/gui/button.cpp.i
.PHONY : src/modules/widgets/gui/button.i

# target to preprocess a source file
src/modules/widgets/gui/button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/modules/widgets/gui/button.cpp.i
.PHONY : src/modules/widgets/gui/button.cpp.i

src/modules/widgets/gui/button.s: src/modules/widgets/gui/button.cpp.s
.PHONY : src/modules/widgets/gui/button.s

# target to generate assembly for a file
src/modules/widgets/gui/button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/modules/widgets/gui/button.cpp.s
.PHONY : src/modules/widgets/gui/button.cpp.s

src/modules/widgets/gui/image.o: src/modules/widgets/gui/image.cpp.o
.PHONY : src/modules/widgets/gui/image.o

# target to build an object file
src/modules/widgets/gui/image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/modules/widgets/gui/image.cpp.o
.PHONY : src/modules/widgets/gui/image.cpp.o

src/modules/widgets/gui/image.i: src/modules/widgets/gui/image.cpp.i
.PHONY : src/modules/widgets/gui/image.i

# target to preprocess a source file
src/modules/widgets/gui/image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/modules/widgets/gui/image.cpp.i
.PHONY : src/modules/widgets/gui/image.cpp.i

src/modules/widgets/gui/image.s: src/modules/widgets/gui/image.cpp.s
.PHONY : src/modules/widgets/gui/image.s

# target to generate assembly for a file
src/modules/widgets/gui/image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/modules/widgets/gui/image.cpp.s
.PHONY : src/modules/widgets/gui/image.cpp.s

src/modules/widgets/gui/keyboard.o: src/modules/widgets/gui/keyboard.cpp.o
.PHONY : src/modules/widgets/gui/keyboard.o

# target to build an object file
src/modules/widgets/gui/keyboard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/modules/widgets/gui/keyboard.cpp.o
.PHONY : src/modules/widgets/gui/keyboard.cpp.o

src/modules/widgets/gui/keyboard.i: src/modules/widgets/gui/keyboard.cpp.i
.PHONY : src/modules/widgets/gui/keyboard.i

# target to preprocess a source file
src/modules/widgets/gui/keyboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/modules/widgets/gui/keyboard.cpp.i
.PHONY : src/modules/widgets/gui/keyboard.cpp.i

src/modules/widgets/gui/keyboard.s: src/modules/widgets/gui/keyboard.cpp.s
.PHONY : src/modules/widgets/gui/keyboard.s

# target to generate assembly for a file
src/modules/widgets/gui/keyboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/modules/widgets/gui/keyboard.cpp.s
.PHONY : src/modules/widgets/gui/keyboard.cpp.s

src/modules/widgets/gui/label.o: src/modules/widgets/gui/label.cpp.o
.PHONY : src/modules/widgets/gui/label.o

# target to build an object file
src/modules/widgets/gui/label.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/modules/widgets/gui/label.cpp.o
.PHONY : src/modules/widgets/gui/label.cpp.o

src/modules/widgets/gui/label.i: src/modules/widgets/gui/label.cpp.i
.PHONY : src/modules/widgets/gui/label.i

# target to preprocess a source file
src/modules/widgets/gui/label.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/modules/widgets/gui/label.cpp.i
.PHONY : src/modules/widgets/gui/label.cpp.i

src/modules/widgets/gui/label.s: src/modules/widgets/gui/label.cpp.s
.PHONY : src/modules/widgets/gui/label.s

# target to generate assembly for a file
src/modules/widgets/gui/label.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/modules/widgets/gui/label.cpp.s
.PHONY : src/modules/widgets/gui/label.cpp.s

src/modules/widgets/touchManager.o: src/modules/widgets/touchManager.cpp.o
.PHONY : src/modules/widgets/touchManager.o

# target to build an object file
src/modules/widgets/touchManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/modules/widgets/touchManager.cpp.o
.PHONY : src/modules/widgets/touchManager.cpp.o

src/modules/widgets/touchManager.i: src/modules/widgets/touchManager.cpp.i
.PHONY : src/modules/widgets/touchManager.i

# target to preprocess a source file
src/modules/widgets/touchManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/modules/widgets/touchManager.cpp.i
.PHONY : src/modules/widgets/touchManager.cpp.i

src/modules/widgets/touchManager.s: src/modules/widgets/touchManager.cpp.s
.PHONY : src/modules/widgets/touchManager.s

# target to generate assembly for a file
src/modules/widgets/touchManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PaxOS8.dir/build.make CMakeFiles/PaxOS8.dir/src/modules/widgets/touchManager.cpp.s
.PHONY : src/modules/widgets/touchManager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... PaxOS8"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/apps/calcul/calcul.o"
	@echo "... src/apps/calcul/calcul.i"
	@echo "... src/apps/calcul/calcul.s"
	@echo "... src/apps/contact/contact.o"
	@echo "... src/apps/contact/contact.i"
	@echo "... src/apps/contact/contact.s"
	@echo "... src/apps/launcher.o"
	@echo "... src/apps/launcher.i"
	@echo "... src/apps/launcher.s"
	@echo "... src/apps/message/message.o"
	@echo "... src/apps/message/message.i"
	@echo "... src/apps/message/message.s"
	@echo "... src/apps/phone/phone.o"
	@echo "... src/apps/phone/phone.i"
	@echo "... src/apps/phone/phone.s"
	@echo "... src/apps/settings/settings.o"
	@echo "... src/apps/settings/settings.i"
	@echo "... src/apps/settings/settings.s"
	@echo "... src/drivers/GSM/Sim800L/sim.o"
	@echo "... src/drivers/GSM/Sim800L/sim.i"
	@echo "... src/drivers/GSM/Sim800L/sim.s"
	@echo "... src/drivers/button/button.o"
	@echo "... src/drivers/button/button.i"
	@echo "... src/drivers/button/button.s"
	@echo "... src/drivers/screen/LovyanGFX/LGFX_SDL.o"
	@echo "... src/drivers/screen/LovyanGFX/LGFX_SDL.i"
	@echo "... src/drivers/screen/LovyanGFX/LGFX_SDL.s"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.o"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.i"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/Fonts/IPA/lgfx_font_japan.s"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.o"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.i"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_cn.s"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.o"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.i"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_ja.s"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.o"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.i"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_kr.s"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.o"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.i"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/Fonts/efont/lgfx_efont_tw.s"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_pngle.o"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_pngle.i"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_pngle.s"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qoi.o"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qoi.i"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qoi.s"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qrcode.o"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qrcode.i"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_qrcode.s"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_tjpgd.o"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_tjpgd.i"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/utility/lgfx_tjpgd.s"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/utility/miniz.o"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/utility/miniz.i"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/utility/miniz.s"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/LGFXBase.o"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/LGFXBase.i"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/LGFXBase.s"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Button.o"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Button.i"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Button.s"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Sprite.o"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Sprite.i"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/LGFX_Sprite.s"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/lgfx_fonts.o"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/lgfx_fonts.i"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/lgfx_fonts.s"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.o"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.i"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/misc/DividedFrameBuffer.s"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/misc/SpriteBuffer.o"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/misc/SpriteBuffer.i"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/misc/SpriteBuffer.s"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/misc/common_function.o"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/misc/common_function.i"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/misc/common_function.s"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/misc/pixelcopy.o"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/misc/pixelcopy.i"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/misc/pixelcopy.s"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_Device.o"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_Device.i"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_Device.s"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.o"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.i"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/panel/Panel_FrameBufferBase.s"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.o"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.i"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/Panel_sdl.s"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/common.o"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/common.i"
	@echo "... src/drivers/screen/LovyanGFX/lgfx/v1/platforms/sdl/common.s"
	@echo "... src/drivers/storage/storage/storage.o"
	@echo "... src/drivers/storage/storage/storage.i"
	@echo "... src/drivers/storage/storage/storage.s"
	@echo "... src/modules/lua/lua.o"
	@echo "... src/modules/lua/lua.i"
	@echo "... src/modules/lua/lua.s"
	@echo "... src/modules/shell/shell.o"
	@echo "... src/modules/shell/shell.i"
	@echo "... src/modules/shell/shell.s"
	@echo "... src/modules/widgets/gui.o"
	@echo "... src/modules/widgets/gui.i"
	@echo "... src/modules/widgets/gui.s"
	@echo "... src/modules/widgets/gui/button.o"
	@echo "... src/modules/widgets/gui/button.i"
	@echo "... src/modules/widgets/gui/button.s"
	@echo "... src/modules/widgets/gui/image.o"
	@echo "... src/modules/widgets/gui/image.i"
	@echo "... src/modules/widgets/gui/image.s"
	@echo "... src/modules/widgets/gui/keyboard.o"
	@echo "... src/modules/widgets/gui/keyboard.i"
	@echo "... src/modules/widgets/gui/keyboard.s"
	@echo "... src/modules/widgets/gui/label.o"
	@echo "... src/modules/widgets/gui/label.i"
	@echo "... src/modules/widgets/gui/label.s"
	@echo "... src/modules/widgets/touchManager.o"
	@echo "... src/modules/widgets/touchManager.i"
	@echo "... src/modules/widgets/touchManager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/gabriel/Bureau/paxos_8_re/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

